### PR TITLE
AWS installation scripts added

### PR DESCRIPTION
**Pull request by pjoshi751**
1. Terraform scripts added to deploy sandbox on AWS
2. Ansible code modified accordingly
3.  Hostnames modified in hosts.ini
4.  CentOS 7.8  image used on console and all kubernetes machines.

### CODE REVIEW

**Comment by rudolphp** [comment]
After this merge, there seems to be an issue in deployment scripts.
When I run step `./keys.sh hosts.ini`
I get below errror.
`
TASK [Gathering Facts] ****************************************************************************************************************
fatal: [console.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname console.sb: Name or service not known", "unreachable": true}
`

**Comment by pjoshi751** [comment]
Hi.. yes, have added ".sb" extension to all hostnames.  This was done because a domain needs to be specified in AWS installation. Please remove the ".sb" suffix in the hosts.ini.  

Are you installing on any cloud infrastructure?  In which case it may be better to exchange keys by some other mechanism (like the way we've done in the terraform/aws/sandbox scripts.

**Comment by rudolphp** [comment]
I have been testing deployment on Azure. 
Yesterday I was able to deploy the backend. But pre-registration was not getting deployed. Was getting errors like below. So was trying it again today.

`
TASK [postgres-init : Run mosip_audit shell script] ***********************************************************************************
fatal: [console]: FAILED! => {"changed": true, "cmd": "bash mosip_audit_db_deploy.sh mosip_audit_deploy.properties", "delta": "0:00:00.086630", "end": "2020-07-16 09:35:07.421949", "msg": "non-zero return code", "rc": 2, "start": "2020-07-16 09:35:07.335319", "stderr": "psql: could not connect to server: Connection refused\n\tIs the server running on host \"mzworker0\" (10.0.0.7) and accepting\n\tTCP/IP connections on port 30090?", "stderr_lines": ["psql: could not connect to server: Connection refused", "\tIs the server running on host \"mzworker0\" (10.0.0.7) and accepting", "\tTCP/IP connections on port 30090?"], "stdout": "07/16/2020 09:35:07 : mosip_audit_deploy.properties\n07/16/2020 09:35:07 : Property file \"mosip_audit_deploy.properties\" found.\n07/16/2020 09:35:07 : ------------------ Database server and service status check for mosip_audit------------------------", "stdout_lines": ["07/16/2020 09:35:07 : mosip_audit_deploy.properties", "07/16/2020 09:35:07 : Property file \"mosip_audit_deploy.properties\" found.", "07/16/2020 09:35:07 : ------------------ Database server and service status check for mosip_audit------------------------"]}

TASK [postgres-init : Run mosip_audit shell script] ***********************************************************************************
fatal: [console]: FAILED! => {"changed": true, "cmd": "bash mosip_audit_db_deploy.sh mosip_audit_deploy.properties", "delta": "0:00:00.102279", "end": "2020-07-16 09:40:08.889167", "msg": "non-zero return code", "rc": 2, "start": "2020-07-16 09:40:08.786888", "stderr": "psql: could not connect to server: Connection refused\n\tIs the server running on host \"mzworker0\" (10.0.0.7) and accepting\n\tTCP/IP connections on port 30090?", "stderr_lines": ["psql: could not connect to server: Connection refused", "\tIs the server running on host \"mzworker0\" (10.0.0.7) and accepting", "\tTCP/IP connections on port 30090?"], "stdout": "07/16/2020 09:40:08 : mosip_audit_deploy.properties\n07/16/2020 09:40:08 : Property file \"mosip_audit_deploy.properties\" found.\n07/16/2020 09:40:08 : ------------------ Database server and service status check for mosip_audit------------------------", "stdout_lines": ["07/16/2020 09:40:08 : mosip_audit_deploy.properties", "07/16/2020 09:40:08 : Property file \"mosip_audit_deploy.properties\" found.", "07/16/2020 09:40:08 : ------------------ Database server and service status check for mosip_audit------------------------"]}

TASK [helm : Install chart kernel] ****************************************************************************************************
fatal: [console]: FAILED! => {"changed": true, "cmd": ["/home/mosipuser/bin/helm", "--kubeconfig", "/home/mosipuser/.kube/mzcluster.config", "install", "kernel", "/home/mosipuser/mosip-infra/deployment/sandbox-v2/helm/charts/kernel", "-f", "/home/mosipuser/mosip-infra/deployment/sandbox-v2/helm/charts/kernel/values.yaml", "-n", "default", "--wait", "--timeout", "20m0s"], "delta": "0:20:04.135913", "end": "2020-07-16 12:11:23.463378", "msg": "non-zero return code", "rc": 1, "start": "2020-07-16 11:51:19.327465", "stderr": "Error: timed out waiting for the condition", "stderr_lines": ["Error: timed out waiting for the condition"], "stdout": "", "stdout_lines": []}

TASK [postgres-init : Run mosip_audit shell script] ***********************************************************************************
fatal: [console]: FAILED! => {"changed": true, "cmd": "bash mosip_audit_db_deploy.sh mosip_audit_deploy.properties", "delta": "0:00:00.104560", "end": "2020-07-16 13:07:15.647760", "msg": "non-zero return code", "rc": 2, "start": "2020-07-16 13:07:15.543200", "stderr": "psql: could not connect to server: Connection refused\n\tIs the server running on host \"mzworker0\" (10.0.0.7) and accepting\n\tTCP/IP connections on port 30090?", "stderr_lines": ["psql: could not connect to server: Connection refused", "\tIs the server running on host \"mzworker0\" (10.0.0.7) and accepting", "\tTCP/IP connections on port 30090?"], "stdout": "07/16/2020 13:07:15 : mosip_audit_deploy.properties\n07/16/2020 13:07:15 : Property file \"mosip_audit_deploy.properties\" found.\n07/16/2020 13:07:15 : ------------------ Database server and service status check for mosip_audit------------------------", "stdout_lines": ["07/16/2020 13:07:15 : mosip_audit_deploy.properties", "07/16/2020 13:07:15 : Property file \"mosip_audit_deploy.properties\" found.", "07/16/2020 13:07:15 : ------------------ Database server and service status check for mosip_audit------------------------"]}
`

**Comment by pjoshi751** [comment]
Are all the machines accessible from console password-less using hostnames in hostis.ini?

$ ssh root@mzworker0  

Also if the above is fine, is port 30090 on mzworker0 accessible.  Is postgres running fine?

**Comment by rudolphp** [comment]
> Hi.. yes, have added ".sb" extension to all hostnames. This was done because a domain needs to be specified in AWS installation. Please remove the ".sb" suffix in your hosts.ini.
> 
> Are you installing on any cloud infrastructure? In which case it may be better to exchange keys by some other mechanism (like the way we've done in the `terraform/aws/sandbox` scripts.

Thanks for the response. It seems like there are many places I will need to remove '.sb'. It is also there in group_vars/all.yml. Will your team not make the hostname consist in azure files also? Thank you.

**Comment by rudolphp** [comment]
I made the changes in group_vars/all.yml and ran install script. Get bellow error. It seems there are other place where the hostnames need to be updated.

`TASK [k8scluster/kubernetes/node : Join to Kubernetes cluster] ************************************************************************
fatal: [mzworker0]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: u\"hostvars['mzmaster.sb']\" is undefined\n\nThe error appears to be in '/home/mosipuser/mosip-infra/deployment/sandbox-v2/roles/k8scluster/kubernetes/node/tasks/join.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Join to Kubernetes cluster\n  ^ here\n"}
fatal: [mzworker1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: u\"hostvars['mzmaster.sb']\" is undefined\n\nThe error appears to be in '/home/mosipuser/mosip-infra/deployment/sandbox-v2/roles/k8scluster/kubernetes/node/tasks/join.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Join to Kubernetes cluster\n  ^ here\n"}
fatal: [mzworker2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: u\"hostvars['mzmaster.sb']\" is undefined\n\nThe error appears to be in '/home/mosipuser/mosip-infra/deployment/sandbox-v2/roles/k8scluster/kubernetes/node/tasks/join.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Join to Kubernetes cluster\n  ^ here\n"}`

**Comment by pjoshi751** [comment]
Will be better to change your hostnames to "*.sb".    There are some unavoidable repetitions of  hostnames in the Ansible scripts.  I could not figure out a way to read them from a single source.

**Comment by rudolphp** [comment]
Hi, I added ".sb" to all hostnames. But get below error
`[mosipuser@console sandbox-v2]$ ./keys.sh hosts.ini
SSH password:
BECOME password[defaults to SSH password]:

PLAY [all] ****************************************************************************************************************************
TASK [Gathering Facts] ****************************************************************************************************************
fatal: [mzmaster.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname mzmaster.sb: Name or service not known", "unreachable": true}
fatal: [mzworker0.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname mzworker0.sb: Name or service not known", "unreachable": true}
fatal: [mzworker2.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname mzworker2.sb: Name or service not known", "unreachable": true}
fatal: [dmzmaster.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dmzmaster.sb: Name or service not known", "unreachable": true}
fatal: [dmzworker0.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dmzworker0.sb: Name or service not known", "unreachable": true}
fatal: [mzworker1.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname mzworker1.sb: Name or service not known", "unreachable": true}
ok: [console.sb]

TASK [Create keys] ********************************************************************************************************************
ok: [console.sb]

TASK [Update authorized keys] *********************************************************************************************************
ok: [console.sb]

TASK [Stop firewalld] *****************************************************************************************************************
changed: [console.sb]

TASK [Disable firewalld] **************************************************************************************************************
changed: [console.sb]

PLAY [console] ************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [console.sb]

TASK [Update authorized keys] *********************************************************************************************************
ok: [console.sb]

PLAY RECAP ****************************************************************************************************************************
console.sb                 : ok=7    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
dmzmaster.sb               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
dmzworker0.sb              : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
mzmaster.sb                : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
mzworker0.sb               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
mzworker1.sb               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
mzworker2.sb               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0`

**Comment by pjoshi751** [comment]
The machines must be accessible by the new hostnames.

**Comment by rudolphp** [comment]
Hi, I want to test the deployment as a user. I don't want to make changes in the source code.  
The Azure deployment was working before by just following the steps in README. But after this PR, it stopped. So wanted to bring it to your teams attention. 
Since the Azure deployment is unstable. Do you suggest I test AWS deployment. If AWS is stable I can give a try.
Thank you.

**Comment by pjoshi751** [comment]
Actually the deployment is not specific to AWS.  Just that since we were migrating to AWS we ended up writing scripts for AWS where some changes were needed like changing hostnames.  Other than that, the setup is the same.  In your case 

fatal: [mzmaster.sb]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve
 hostname mzmaster.sb: Name or service not known", "unreachable": true}.

If you can move to AWS that will be good because you can try the Terraform scripts to setup.  The keys are exchanged as part of the setup instead of using the current method of having a mosipuser password and running keys.sh.   We are using the same Terraform scripts now.   I can help you with that.
The above means that these machines are not accessible with 'mosipuser' name and password.  



The above means that Ansible is not able to reach to the machines.    Can you try `ssh root@mzmaster.sb` and let me know if it works.   If it doesn't, that

**Comment by rudolphp** [comment]
I am test AWS deploy using the README https://github.com/mosip/mosip-infra/tree/master/deployment/sandbox-v2/terraform/aws/sandbox
Get below error on 'terraform plan' step

`rudolph@AG-LT-007:/mnt/c/Projects/mosip-infra/deployment/sandbox-v2/terraform/aws/sandbox$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: xxxxxxxx-xxxxx-xxxx-xxxxx

  on main.tf line 1, in provider "aws":
   1: provider "aws" {
`

**Comment by pjoshi751** [comment]
Looks like AWS credentials issue?
```
export AWS_ACCESS_KEY_ID=<>
export AWS_SECRET_ACCESS_KEY=<>
```

**Comment by rudolphp** [comment]
The deployment was done on AWS. Thanks.
Now in "Hosted Zones" I see Domain name as "sb". How can I give my domain name?
`sandbox_name` in `variables.tf` I gave `csftest'

hosted

**Comment by pjoshi751** [comment]
Yes, .sb is the private domain, that's how all machines will be addressed.  So this looks good.   `sandbox_name` could be anything - it's just informational.
 
You will have to register a domain name for the same box  for external access.  We obtained domain name "mosip.net" from Route53 Registrar.

**Comment by pjoshi751** [comment]
Also, do note that we are running m5a.xlarge instances.  Just keep a tab on the costs ;)

**Comment by rudolphp** [comment]
getting below error when I ssh from console. Note the user name was 'centos' for console. 'root' did not work.

`[centos@console ~]$ ssh root@mzworker0.sb
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).`

**Comment by pjoshi751** [comment]
Yes, you have to login to console with centos, then 'sudo su mosipuser'.   Then trying connecting to other machines.  I think I should update the documentation

**Comment by rudolphp** [comment]
I ran the ansible command `ansible-playbook -i hosts.ini site.yml` with mosipuser, it stopped at below error

`TASK [letsencrypt : run certbot] ******************************************************************************************************
fatal: [console.sb]: FAILED! => {"changed": true, "cmd": ["/home/mosipuser/.venv-py3/bin/certbot", "certonly", "--nginx", "-n", "-m", "info@mosip.io", "--agree-tos", "-d", "dataforall.info"], "delta": "0:00:07.370835", "end": "2020-07-21 10:52:28.095178", "msg": "non-zero return code", "rc": 1, "start": "2020-07-21 10:52:20.724343", "stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenticator nginx, Installer nginx\nObtaining a new certificate\nPerforming the following challenges:\nhttp-01 challenge for dataforall.info\nWaiting for verification...\nChallenge failed for domain dataforall.info\nhttp-01 challenge for dataforall.info\nCleaning up challenges\nSome challenges have failed.", "stderr_lines": ["Saving debug log to /var/log/letsencrypt/letsencrypt.log", "Plugins selected: Authenticator nginx, Installer nginx", "Obtaining a new certificate", "Performing the following challenges:", "http-01 challenge for dataforall.info", "Waiting for verification...", "Challenge failed for domain dataforall.info", "http-01 challenge for dataforall.info", "Cleaning up challenges", "Some challenges have failed."], "stdout": "IMPORTANT NOTES:\n - The following errors were reported by the server:\n\n   Domain: dataforall.info\n   Type:   dns\n   Detail: DNS problem: SERVFAIL looking up A for dataforall.info -\n   the domain's nameservers may be malfunctioning\n - Your account credentials have been saved in your Certbot\n   configuration directory at /etc/letsencrypt. You should make a\n   secure backup of this folder now. This configuration directory will\n   also contain certificates and private keys obtained by Certbot so\n   making regular backups of this folder is ideal.", "stdout_lines": ["IMPORTANT NOTES:", " - The following errors were reported by the server:", "", "   Domain: dataforall.info", "   Type:   dns", "   Detail: DNS problem: SERVFAIL looking up A for dataforall.info -", "   the domain's nameservers may be malfunctioning", " - Your account credentials have been saved in your Certbot", "   configuration directory at /etc/letsencrypt. You should make a", "   secure backup of this folder now. This configuration directory will", "   also contain certificates and private keys obtained by Certbot so", "   making regular backups of this folder is ideal."]}

PLAY RECAP ****************************************************************************************************************************
console.sb                 : ok=29   changed=21   unreachable=0    failed=1    skipped=1    rescued=0    ignored=0`

**Comment by pjoshi751** [comment]
What's your domain name.  Is it registered?  Basically Letsencrypt is trying to issue certificate for your domain - it's failing there.

**Comment by rudolphp** [comment]
We have taken the domain dataforall.info from network solutions. Does the domain have to be from AWS Route 53??

**Comment by pjoshi751** [comment]
No.  You will have to just point it to the public ip of the console.   Do you already have SSL certificates for the domain?  If yes, we can disable the Letsencrypt part  (README mentions that).

**Comment by rudolphp** [comment]
The home page is loading https://dataforall.info/
The ansible command hangs and ssh disconnects. So I connect and run the ansible command again. I think it picking-up from where it breaks (this is good). 
Finally the ansible command gave below error.
`TASK [keycloak-init : Get admin token] ************************************************************************************************
fatal: [console.sb]: FAILED! => {"changed": false, "content": "", "elapsed": 30, "msg": "Status code was -1 and not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://mzworker0.sb:30080/keycloak/auth/realms/master/protocol/openid-connect/token"}

PLAY RECAP ****************************************************************************************************************************
console.sb                 : ok=220  changed=41   unreachable=0    failed=1    skipped=19   rescued=0    ignored=2
dmzmaster.sb               : ok=34   changed=8    unreachable=0    failed=0    skipped=30   rescued=0    ignored=0
dmzworker0.sb              : ok=23   changed=3    unreachable=0    failed=0    skipped=28   rescued=0    ignored=0
mzmaster.sb                : ok=34   changed=8    unreachable=0    failed=0    skipped=30   rescued=0    ignored=0
mzworker0.sb               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
mzworker1.sb               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
mzworker2.sb               : ok=23   changed=3    unreachable=0    failed=0    skipped=28   rescued=0    ignored=0`

Our goal is to install the pre registration module and start testing the frontend.

P.S - for mz I configured 3 workers instead of 8. Hope this is ok?

**Comment by pjoshi751** [comment]
mzworker0.sb : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
mzworker1.sb : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0

Are these two reachable from console?

Yes, 3 workers are ok for just Pre Reg

**Comment by rudolphp** [comment]
Fails at bellow error.
`TASK [postgres-init : Run mosip_prereg shell script] **********************************************************************************
fatal: [console.sb]: FAILED! => {"changed": true, "cmd": "bash mosip_prereg_db_deploy.sh mosip_prereg_deploy.properties", "delta": "0:00:03.867995", "end": "2020-07-22 06:31:43.074447", "msg": "non-zero return code", "rc": 2, "start": "2020-07-22 06:31:39.206452", "stderr": "", "stderr_lines": [], "stdout": "07/22/2020 06:31:39 : mosip_prereg_deploy.properties\n07/22/2020 06:31:39 : Property file \"mosip_prereg_deploy.properties\" found.\n07/22/2020 06:31:39 : ------------------ Database server and service status check for mosip_prereg------------------------\n07/22/2020 06:31:39 : Postgres database server and service is up and running\n07/22/2020 06:31:39 : ----------------------------------------------------------------------------------------\n07/22/2020 06:31:39 : Started sourcing the mosip_prereg Database scripts\n07/22/2020 06:31:39 : Database scripts are sourcing from :/tmp/mosip/pre-registration/db_scripts\n07/22/2020 06:31:39 : Database deployment on mosip_prereg database is started....\n07/22/2020 06:31:39 : Checking for existing users.... Count of existing users: 3\n07/22/2020 06:31:39 : Database users already exist\n07/22/2020 06:31:39 : No active database connections exist on mosip_prereg\n07/22/2020 06:31:39 : Prereg user already exist", "stdout_lines": ["07/22/2020 06:31:39 : mosip_prereg_deploy.properties", "07/22/2020 06:31:39 : Property file \"mosip_prereg_deploy.properties\" found.", "07/22/2020 06:31:39 : ------------------ Database server and service status check for mosip_prereg------------------------", "07/22/2020 06:31:39 : Postgres database server and service is up and running", "07/22/2020 06:31:39 : ----------------------------------------------------------------------------------------", "07/22/2020 06:31:39 : Started sourcing the mosip_prereg Database scripts", "07/22/2020 06:31:39 : Database scripts are sourcing from :/tmp/mosip/pre-registration/db_scripts", "07/22/2020 06:31:39 : Database deployment on mosip_prereg database is started....", "07/22/2020 06:31:39 : Checking for existing users.... Count of existing users: 3", "07/22/2020 06:31:39 : Database users already exist", "07/22/2020 06:31:39 : No active database connections exist on mosip_prereg", "07/22/2020 06:31:39 : Prereg user already exist"]}`

**Comment by pjoshi751** [comment]
No active database connections exist on mosip_prereg\n07/22/2020 06:31:39 : Prereg user already exist", "stdout_lines": ["07/22/2020 06:31:39 :      Is postgres up?      And it is accessed via  nodeport  30090.    So from console this port must be accessible on mzworker0.sb.

**Comment by rudolphp** [comment]
We get below error on telnet
Where are these connections established. In Azure we ran 'keys.sh hosts.ini' such step seem to be missing in AWS.

`[mosipuser@console centos]$ telnet mzworker0.sb 30080
Trying 10.20.20.37...
telnet: connect to address 10.20.20.37: Connection refused
[mosipuser@console centos]$ telnet mzworker0.sb 30090
Trying 10.20.20.37...
telnet: connect to address 10.20.20.37: Connection refused`

**Comment by pjoshi751** [comment]
that's not needed 'cause the key exchange is done using terraform scripts

**Comment by rudolphp** [comment]
CentOS Linux release 7.8.2003 (Core)

I have not made any changes in the default scripts. What should we do now?
The 'kube' network groups also looks fine in AWS

**Comment by pjoshi751** [comment]
Can you come over Slack? I will add to to a channel.  Please send your slack id to info@mosip.io, with your name and reference.

**Comment by rudolphp** [comment]
I have sent my slack details to info@mosip.io

**Pull request merged**
