### PR TITLE
[MOSIP-27446]Updated prop_comparator.py file.

### PR DESCRIPTION
**Pull request by Mohanraj209**

### CODE REVIEW

**Review by ckm007 — CHANGES_REQUESTED** [review]
add this version of comparator script in utils of v3 frommosip-infra.

**Comment by Mohanraj209** [comment]
> add this version of comparator script in utils of v3 frommosip-infra.

Updated sir.

**Review by ckm007 — CHANGES_REQUESTED** [review]
Can we add Readme.md explaining the use, and  need for the script.

**Comment by Mohanraj209** [comment]
> Can we add Readme.md explaining the use, and need for the script.

Updated README.md file sir.

**Review by ckm007 — APPROVED** [review]

**Pull request merged**
