### PR TITLE
MOSIP-10835 : Kafka cluster helm chart added with respective config to sandbox

### PR DESCRIPTION
**Pull request by vishwa-vyom**
Kafka cluster helm chart added with respective config to sandbox

### CODE REVIEW

**Review by pjoshi751 — COMMENTED** [review]
Pod parameters like replicas etc, we specify in a separate file `podconfig.yml` so that for any given installation these values may be modified without having to touch `group_vars.yml`.  Please see if this can be done here.

**Comment by vishwa-vyom** [comment]
@pjoshi751 I though about this, but there was a connectivity between replica count config and replication factor config, so I dint move the replicate count to podconfig.yml. But I will move it to podconfig.yml with respective comments in both places.

**Comment by pjoshi751** [comment]
If there is a connection, then let them be at one place.  That's fine.

**Comment by vishwa-vyom** [comment]
ok

**Pull request merged**
